export const tailwindConfig = {
    theme: {
      extend: {
        colors: {
          background: "#F7F5E6",
          foreground: "#4A4E42",
          card: "#F7F5E6",
          "card-foreground": "#2E2F2B",
          popover: "#FFFFFF",
          "popover-foreground": "#3C3F36",
          primary: "#C75000",
          "primary-foreground": "#FFFFFF",
          secondary: "#E8E4CF",
          "secondary-foreground": "#6B695C",
          muted: "#EBE7C6",
          "muted-foreground": "#9C9986",
          accent: "#E8E4CF",
          "accent-foreground": "#3C3F36",
          destructive: "#8B1D07",
          "destructive-foreground": "#FFDBD2",
          border: "#DEDAC3",
          input: "#BDBA9E",
          ring: "#4E5AD4",
          "chart-1": "#A94408",
          "chart-2": "#A135BF",
          "chart-3": "#DED9B8",
          "chart-4": "#D9D2E0",
          "chart-5": "#A64509",
          sidebar: "#F5F3DD",
          "sidebar-foreground": "#56584D",
          "sidebar-primary": "#C75000",
          "sidebar-primary-foreground": "#FCFCFC",
          "sidebar-accent": "#E8E4CF",
          "sidebar-accent-foreground": "#535353",
          "sidebar-border": "#EFEFEF",
          "sidebar-ring": "#C5C5C5",
          "shadow-color": "#000000",
        },
        fontFamily: {
          sans: [
            "ui-sans-serif",
            "system-ui",
            "-apple-system",
            "BlinkMacSystemFont",
            '"Segoe UI"',
            "Roboto",
            '"Helvetica Neue"',
            "Arial",
            '"Noto Sans"',
            "sans-serif",
            '"Apple Color Emoji"',
            '"Segoe UI Emoji"',
            '"Segoe UI Symbol"',
            '"Noto Color Emoji"',
          ],
          serif: [
            "ui-serif",
            "Georgia",
            "Cambria",
            '"Times New Roman"',
            "Times",
            "serif",
          ],
          mono: [
            "ui-monospace",
            "SFMono-Regular",
            "Menlo",
            "Monaco",
            "Consolas",
            '"Liberation Mono"',
            '"Courier New"',
            "monospace",
          ],
        },
        borderRadius: {
          DEFAULT: "0.5rem",
          sm: "0.25rem",
          md: "0.375rem",
          lg: "0.5rem",
          xl: "0.75rem",
        },
        spacing: {
          DEFAULT: "0.25rem",
        },
        letterSpacing: {
          normal: "0em",
          tighter: "-0.05em",
          tight: "-0.025em",
          wide: "0.025em",
          wider: "0.05em",
          widest: "0.1em",
        },
        boxShadow: {
          "2xs": "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
          xs: "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
          sm: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
          DEFAULT: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
          md: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.1)",
          lg: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 4px 6px -1px rgba(0, 0, 0, 0.1)",
          xl: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 8px 10px -1px rgba(0, 0, 0, 0.1)",
          "2xl": "0 1px 3px 0 rgba(0, 0, 0, 0.25)",
        },
      },
    },
  };